services:
  - type: web
    name: vendorportal-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        sync: false # set manually in Render dashboard — do not commit real value here
      - key: AllowedOrigins
        value: https://vendorportal-frontend-rxwy.onrender.com,https://vendorportal-frontend.onrender.com,http://localhost:4200,http://localhost:4201
      - key: Jwt__Key
        sync: false # set manually in Render dashboard — do not commit real value here
      - key: Jwt__Issuer
        value: WebProlific
      - key: Jwt__Audience
        value: WebProlific
      - key: DOTNET_hostBuilder__reloadConfigOnChange
        value: "false"

  - type: static
    name: vendorportal-frontend
    rootDir: frontend/supplier-portal
    buildCommand: npm install && npm run build
    staticPublishPath: dist/supplier-portal/browser
    envVars:
      - key: NODE_VERSION
        value: 20
