services:
  - type: web
    name: vendorportal-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        value: Server=182.78.194.30\\SQL2017,2017;Database=WebProlific;User Id=opm1;Password=;TrustServerCertificate=True;MultipleActiveResultSets=true
      - key: AllowedOrigins
        value: https://vendorportal-frontend-rxwy.onrender.com,https://vendorportal-frontend.onrender.com,http://localhost:4200,http://localhost:4201
      - key: Jwt__Key
        value: DevSecretKey_ChangeInProduction_32Chars!
      - key: Jwt__Issuer
        value: WebProlific
      - key: Jwt__Audience
        value: WebProlific

  - type: static
    name: vendorportal-frontend
    rootDir: frontend/supplier-portal
    buildCommand: npm install && npm run build
    staticPublishPath: dist/supplier-portal/browser
    envVars:
      - key: NODE_VERSION
        value: 20
