// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProlific.Infrastructure.Data;

#nullable disable

namespace WebProlific.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719130000_FixGstinNullableAndFilteredIndex")]
    partial class FixGstinNullableAndFilteredIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebProlific.Core.Entities.AppUser", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsInternal")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastLoginAt")
                    .HasColumnType("datetime2");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Role")
                    .HasColumnType("int");

                b.Property<Guid?>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.BuyingEntity", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Region")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("BuyingEntities");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.Catalogue", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ApprovedDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("BuyingEntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("RejectionReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<DateTime>("SubmittedDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("BuyingEntityId");

                b.HasIndex("VendorId");

                b.ToTable("Catalogues");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.CatalogueLine", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CatalogueId")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal?>("ContractPrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal?>("DeviationPercent")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("ItemCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("ItemId")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("TaxClass")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ValidFrom")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ValidTo")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CatalogueId");

                b.HasIndex("ItemId");

                b.ToTable("CatalogueLines");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.DeliveryNote", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DeliveryNoteNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ExpectedDeliveryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Notes")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("PurchaseOrderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("SupportingDocumentUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TimeWindowEnd")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TimeWindowStart")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("PurchaseOrderId");

                b.HasIndex("VendorId");

                b.ToTable("DeliveryNotes");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.DeliveryNoteLine", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("BatchLotNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("DeliveryNoteId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ItemDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("QtyInDelivery")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("DeliveryNoteId");

                b.ToTable("DeliveryNoteLines");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.Invoice", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("InvoiceDate")
                    .HasColumnType("datetime2");

                b.Property<string>("InvoiceNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("InvoicePdfUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("MatchStatus")
                    .HasColumnType("int");

                b.Property<string>("MismatchReasons")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("PurchaseOrderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<decimal>("SubTotal")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TaxAmount")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("TotalAmount")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("PurchaseOrderId");

                b.HasIndex("VendorId");

                b.ToTable("Invoices");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.InvoiceLine", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("ExpectedQty")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("ExpectedUnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("InvoiceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("InvoicedQty")
                    .HasColumnType("decimal(18,2)");

                b.Property<decimal>("InvoicedUnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("ItemDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("LineTotal")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("InvoiceId");

                b.ToTable("InvoiceLines");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.Item", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("BaseUom")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ItemCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("KeySpecs")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NormalisedDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PackSize")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Items");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.ItemDedupCandidate", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ClusterId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsSource")
                    .HasColumnType("bit");

                b.Property<Guid>("ItemId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("MatchedAttributes")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("SimilarityScore")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("ClusterId");

                b.HasIndex("ItemId");

                b.ToTable("ItemDedupCandidates");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.ItemDedupCluster", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("MergedIntoItemId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ModelVersion")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("ResolvedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("ItemDedupClusters");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.KycChangeRequest", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("ActionDate")
                    .HasColumnType("datetime2");

                b.Property<string>("ApprovedBy")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("ApprovedByUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("FieldChanged")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NewValue")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("OldValue")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RejectionReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RequestedBy")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("RequestedByUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("RequestedDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<string>("SupportingDocumentUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("VendorId");

                b.ToTable("KycChangeRequests");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.Notification", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Detail")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsRead")
                    .HasColumnType("bit");

                b.Property<string>("TargetId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TargetScreen")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Type")
                    .HasColumnType("int");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("Notifications");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.Payment", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("Amount")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("InvoiceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("PaidDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PaymentReference")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("ScheduledDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<Guid>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("InvoiceId");

                b.HasIndex("VendorId");

                b.ToTable("Payments");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.Property", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BuyingEntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("City")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Code")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.HasKey("Id");

                b.HasIndex("BuyingEntityId");

                b.ToTable("Properties");
            });

            modelBuilder.Entity("WebProlific.Core.Entities.PurchaseOrder", b => {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AcknowledgmentReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("BuyingEntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("OrderDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PoNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<Guid?>("PropertyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("RequiredByDate")
                    .HasColumnType("datetime2");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<decimal>("TotalValue")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("VendorId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("BuyingEntityId");

                b.HasIndex("PoNumber")
                    .IsUnique();

                b.HasIndex("PropertyId");

                b.ToTable("PurchaseOrders");
            });
        }
    }
}